apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
  namespace: elastic-stack
  labels:
    app: teamcity-agent
    app.kubernetes.io/part-of: elastic-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
        app.kubernetes.io/part-of: elastic-stack
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
        - name: teamcity-agent
          image: jetbrains/teamcity-agent:2023.11-linux-sudo
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            privileged: true
          env:
            - name: SERVER_URL
              value: http://teamcity-server:8111
            - name: AGENT_NAME
              value: k8s-teamcity-agent
            - name: DOCKER_IN_DOCKER
              value: start
            - name: DOCKER_HOST
              value: ""
          volumeMounts:
            - name: docker-data
              mountPath: /var/lib/docker
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 2Gi
          readinessProbe:
            exec:
              command:
                - test
                - -f
                - /data/teamcity_agent/conf/buildAgent.properties
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: docker-data
          emptyDir: {}
