apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - elasticsearch/00-configmap.yaml
  - elasticsearch/01-service.yaml
  - elasticsearch/02-statefulset.yaml
  - kibana/01-deployment.yaml
  - kibana/02-service.yaml
  - apm-server/01-configmap.yaml
  - apm-server/02-deployment.yaml
  - apm-server/03-service.yaml
