apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-stack
  labels:
    app: kibana
    app.kubernetes.io/part-of: elastic-stack
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
