apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data
  namespace: elastic-stack
  labels:
    app: teamcity-server
    app.kubernetes.io/part-of: elastic-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
