server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /proxy/java/ {
        set $java_upstream http://java-app.elastic-stack.svc.cluster.local:8080;
        rewrite ^/proxy/java/(.*)$ /$1 break;
        proxy_set_header traceparent $http_traceparent;
        proxy_set_header tracestate $http_tracestate;
        proxy_pass $java_upstream;
    }

    location /proxy/spring-boot/ {
        set $spring_boot_upstream http://spring-boot-app.elastic-stack.svc.cluster.local:8080;
        rewrite ^/proxy/spring-boot/(.*)$ /$1 break;
        proxy_set_header traceparent $http_traceparent;
        proxy_set_header tracestate $http_tracestate;
        proxy_pass $spring_boot_upstream;
    }

    location /proxy/openliberty/ {
        set $openliberty_upstream http://openliberty-app.elastic-stack.svc.cluster.local:9080;
        rewrite ^/proxy/openliberty/(.*)$ /$1 break;
        proxy_set_header traceparent $http_traceparent;
        proxy_set_header tracestate $http_tracestate;
        proxy_pass $openliberty_upstream;
    }

    location /proxy/expressjs/ {
        set $expressjs_upstream http://expressjs-app.elastic-stack.svc.cluster.local:3000;
        rewrite ^/proxy/expressjs/(.*)$ /$1 break;
        proxy_set_header traceparent $http_traceparent;
        proxy_set_header tracestate $http_tracestate;
        proxy_pass $expressjs_upstream;
    }

    location /proxy/python/ {
        set $python_upstream http://python-app.elastic-stack.svc.cluster.local:5000;
        rewrite ^/proxy/python/(.*)$ /$1 break;
        proxy_set_header traceparent $http_traceparent;
        proxy_set_header tracestate $http_tracestate;
        proxy_pass $python_upstream;
    }

    location /proxy/csharp/ {
        set $csharp_upstream http://csharp-app.elastic-stack.svc.cluster.local:5000;
        rewrite ^/proxy/csharp/(.*)$ /$1 break;
        proxy_set_header traceparent $http_traceparent;
        proxy_set_header tracestate $http_tracestate;
        proxy_pass $csharp_upstream;
    }

    location /proxy/golang/ {
        set $golang_upstream http://golang-app.elastic-stack.svc.cluster.local:8080;
        rewrite ^/proxy/golang/(.*)$ /$1 break;
        proxy_set_header traceparent $http_traceparent;
        proxy_set_header tracestate $http_tracestate;
        proxy_pass $golang_upstream;
    }
}
