apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: elastic-stack
  labels:
    app: elasticsearch
    app.kubernetes.io/part-of: elastic-stack
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-stack
  labels:
    app: elasticsearch
    app.kubernetes.io/part-of: elastic-stack
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
