apiVersion: batch/v1
kind: Job
metadata:
  name: build-java
  namespace: builds
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: checkout
        image: alpine/git:latest
        command: ["/bin/sh", "-c"]
        args: ["git clone --branch main https://github.com/kesi03/apm-tests.git /workspace/source"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=apps/java/Dockerfile"
        - "--context=dir:///workspace/source"
        - "--destination=registry:32000/java-app:latest"
        - "--insecure-registry=registry:32000"
        - "--skip-tls-verify-registry=registry:32000"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: workspace
        emptyDir: {}
      restartPolicy: Never
