apiVersion: batch/v1
kind: Job
metadata:
  name: build-python
  namespace: builds
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=apps/python/Dockerfile"
        - "--context=https://github.com/kesi03/apm-tests.git"
        - "--destination=registry:32000/python-app:latest"
        - "--insecure-registry=registry:32000"
        - "--skip-tls-verify-registry=registry:32000"
      restartPolicy: Never
