apiVersion: batch/v1
kind: Job
metadata:
  name: build-spring-boot
  namespace: builds
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      hostNetwork: true
      initContainers:
      - name: checkout
        image: alpine/git:latest
        command: ["/bin/sh", "-c"]
        args: ["git clone --branch main https://github.com/kesi03/apm-tests.git /workspace/source"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=/workspace/source/apps/spring-boot/Dockerfile"
        - "--context=dir:///workspace/source/apps/spring-boot"
        - "--destination=localhost:32000/spring-boot-app:latest"
        - "--insecure-registry=localhost:32000"
        - "--skip-tls-verify-registry=localhost:32000"
        - "--push-retry=5"
        - "--image-download-retry=5"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: workspace
        emptyDir: {}
      restartPolicy: Never
