apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Demo application workloads
  sourceRepos:
    - https://github.com/kesi03/apm-tests.git
  destinations:
    - namespace: elastic-stack
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/kesi03/apm-tests.git
    targetRevision: HEAD
    path: apps
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
