apiVersion: v1
kind: Secret
metadata:
  name: elastic-apm
  namespace: elastic-stack
  labels:
    app.kubernetes.io/part-of: elastic-stack
type: Opaque
stringData:
  token: QkR1dzRwOEI0a2lFamVIMU9LeGI6b1RsV3BuT1NNcEYwWGpYY0dvWGgzUQ==
