import { config } from '../config';
import { get } from '../http';

const SERVER_APP_URLS = [
  config.apps.java,
  config.apps.springBoot,
  config.apps.openLiberty,
  config.apps.expressjs,
  config.apps.python,
  config.apps.csharp,
  config.apps.golang
];

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

async function listApmIndices(): Promise<string[]> {
  const res = await get(`${config.stack.elasticsearch}/_cat/indices?h=index&format=json`, {
    timeout: 15_000
  });
  if (!Array.isArray(res.body)) {
    return [];
  }
  return (res.body as Array<{ index?: string }>)
    .map((row) => row.index ?? '')
    .filter((name) => name && /apm|traces-|errors-/.test(name));
}

describe('APM data ingestion', () => {
  it('indexes telemetry generated by the demo apps', async () => {
    for (const url of SERVER_APP_URLS) {
      await get(`${url}/`, { timeout: 10_000 }).catch(() => {});
      await get(`${url}/slow`, { timeout: 10_000 }).catch(() => {});
      await get(`${url}/error`, { timeout: 10_000 }).catch(() => {});
    }

    // Agents buffer and flush asynchronously, so poll for the APM data
    // streams (traces/errors/metrics) to appear in Elasticsearch.
    let apmIndices: string[] = [];
    for (let attempt = 0; attempt < 12; attempt += 1) {
      apmIndices = await listApmIndices();
      if (apmIndices.length > 0) {
        break;
      }
      await sleep(5_000);
    }

    console.log(`APM-related indices found: ${apmIndices.join(', ') || 'none'}`);
    expect(apmIndices.length).toBeGreaterThan(0);
  }, 120_000);
});
